{{
    config(
        materialized = 'table'
    )
}}

WITH CUSTOMERS AS (

    SELECT
        *
    FROM {{ ref('stage_customer') }}

)

SELECT
    C.CUSTOMER_KEY,
    C.NAME AS CUSTOMER_NAME,
    C.ADDRESS AS CUSTOMER_ADDRESS,
    C.NATION_KEY,
    C.PHONE_NUMBER AS CUSTOMER_PHONE_NUMBER,
    C.ACCOUNT_BALANCE AS CUSTOMER_ACCOUNT_BALANCE,
    C.MARKET_SEGMENT AS CUSTOMER_MARKET_SEGMENT_NAME
FROM
    CUSTOMERS AS C
ORDER BY
    C.CUSTOMER_KEY
