repos:
  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          - '-c=.yamllint'
  - repo: 'https://github.com/dbt-checkpoint/dbt-checkpoint'
    rev: v1.1.0
    hooks:
      - id: check-script-semicolon
  - repo: 'https://github.com/sqlfluff/sqlfluff'
    rev: 2.3.5
    hooks:
      - id: sqlfluff-lint
        args: ['--dialect', 'snowflake']
        additional_dependencies:
          - dbt-snowflake==1.7.0
          - sqlfluff-templater-dbt==2.3.5
      - id: sqlfluff-fix
        args: ['--dialect', 'snowflake']
        additional_dependencies:
          - dbt-snowflake==1.7.0
          - sqlfluff-templater-dbt==2.3.5
