ops_dbt_digital_tier_automation:
sf_dbt:
  outputs:
    dev:
      account: bslxjyh-dz59805
      user: dbt_cloud_user
      database: dbt_hol_dev
      password: KGWelcome2050!
      role: DBT_DEV_ROLE
      schema: public
      threads: 200
      type: snowflake
      warehouse: dbt_dev_wh
    prod:
      account: bslxjyh-dz59805
      user: dbt_cloud_user
      database: dbt_hol_prod
      password: KGWelcome2050!
      role: DBT_PROD_ROLE
      schema: public
      threads: 200
      type: snowflake
      warehouse: dbt_prod_wh
  target: dev
