WITH CST_MARKET_DAYS AS (
    SELECT DISTINCT DATE
    FROM {{ref('tfm_stock_history_major_currency')}} AS HIST
    WHERE HIST.DATE >= (SELECT MIN(DATE) AS MIN_DT FROM {{ref('tfm_book')}})
)

SELECT
    CST_MARKET_DAYS.DATE,
    TRADER,
    STOCK_EXCHANGE_NAME,
    INSTRUMENT,
    BOOK,
    CURRENCY,
    SUM(VOLUME) AS TOTAL_SHARES
FROM CST_MARKET_DAYS,
    {{ref('tfm_book')}} AS BOOK
WHERE BOOK.DATE <= CST_MARKET_DAYS.DATE
GROUP BY 1, 2, 3, 4, 5, 6
