WITH CST AS (
    SELECT COMPANY_TICKER, COMPANY_NAME, STOCK_EXCHANGE_NAME, INDICATOR_NAME, DATE, VALUE, DATA_SOURCE_NAME
    FROM {{ref('base_knoema_stock_history')}}
    WHERE INDICATOR_NAME IN ('Close', 'Open', 'High', 'Low', 'Volume', 'Change %')
)

SELECT *
FROM CST
PIVOT (SUM(VALUE) FOR INDICATOR_NAME IN ('Close', 'Open', 'High', 'Low', 'Volume', 'Change %'))
    AS P (COMPANY_TICKER, COMPANY_NAME, STOCK_EXCHANGE_NAME, DATE, DATA_SOURCE_NAME, CLOSE, OPEN, HIGH, LOW, VOLUME, CHANGE)
