SELECT
    T.INSTRUMENT, T.STOCK_EXCHANGE_NAME,
    T.DATE, T.TRADER, T.VOLUME, T.COST, T.COST_PER_SHARE, T.CURRENCY,
    SUM(T.COST) OVER (PARTITION BY T.INSTRUMENT, T.STOCK_EXCHANGE_NAME, T.TRADER ORDER BY T.DATE ROWS UNBOUNDED PRECEDING) AS CASH_CUMULATIVE,
    CASE
        WHEN T.CURRENCY = 'GBP' THEN S.GBP_CLOSE
        WHEN T.CURRENCY = 'EUR' THEN S.EUR_CLOSE
        ELSE CLOSE
    END AS CLOSE_PRICE_MATCHING_CCY,
    T.TOTAL_SHARES * CLOSE_PRICE_MATCHING_CCY AS MARKET_VALUE,
    T.TOTAL_SHARES * CLOSE_PRICE_MATCHING_CCY + CASH_CUMULATIVE AS PNL
FROM {{ref('tfm_daily_position_with_trades')}} AS T
INNER JOIN {{ref('tfm_stock_history_major_currency')}} AS S
    ON
        T.INSTRUMENT = S.COMPANY_TICKER
        AND S.DATE = T.DATE
        AND T.STOCK_EXCHANGE_NAME = S.STOCK_EXCHANGE_NAME
