WITH SOURCE AS (

    SELECT
        *
    FROM {{ source('tpch', 'lineitem') }}

),

RENAMED AS (

    SELECT

        (L_ORDERKEY || L_LINENUMBER) AS ORDER_ITEM_KEY,
        L_ORDERKEY AS ORDER_KEY,
        L_PARTKEY AS PART_KEY,
        L_SUPPKEY AS SUPPLIER_KEY,
        L_LINENUMBER AS LINE_NUMBER,
        L_QUANTITY AS QUANTITY,
        L_EXTENDEDPRICE AS EXTENDED_PRICE,
        L_DISCOUNT AS DISCOUNT_PERCENTAGE,
        L_TAX AS TAX_RATE,
        L_RETURNFLAG AS RETURN_FLAG,
        L_LINESTATUS AS LINE_STATUS_CODE,
        L_SHIPDATE AS SHIP_DATE,
        L_COMMITDATE AS COMMIT_DATE,
        L_RECEIPTDATE AS RECEIPT_DATE,
        L_SHIPINSTRUCT AS SHIP_INSTRUCTIONS,
        L_SHIPMODE AS SHIP_MODE_NAME,
        L_COMMENT AS COMMENT

    FROM SOURCE

)

SELECT * FROM RENAMED
