WITH SOURCE AS (

    SELECT
        *
    FROM {{ source('tpch', 'part') }}

),

RENAMED AS (

    SELECT

        P_PARTKEY AS PART_KEY,
        P_NAME AS PART_NAME,
        P_MFGR AS PART_MANUFACTURER_NAME,
        P_BRAND AS PART_BRAND_NAME,
        P_TYPE AS PART_TYPE_NAME,
        P_SIZE AS PART_SIZE,
        P_CONTAINER AS PART_CONTAINER_DESC,
        P_RETAILPRICE AS RETAIL_PRICE,
        P_COMMENT AS PART_COMMENT

    FROM SOURCE

)

SELECT * FROM RENAMED
