SELECT
    BOOK,
    DATE,
    TRADER,
    INSTRUMENT,
    ACTION,
    COST,
    CURRENCY,
    VOLUME,
    COST_PER_SHARE,
    STOCK_EXCHANGE_NAME,
    SUM(T.VOLUME) OVER (PARTITION BY T.INSTRUMENT, T.STOCK_EXCHANGE_NAME, TRADER ORDER BY T.DATE ROWS UNBOUNDED PRECEDING) AS TOTAL_SHARES
FROM {{ref('tfm_book')}} AS T
UNION ALL
SELECT
    BOOK,
    DATE,
    TRADER,
    INSTRUMENT,
    'HOLD' AS ACTION,
    0 AS COST,
    CURRENCY,
    0 AS VOLUME,
    0 AS COST_PER_SHARE,
    STOCK_EXCHANGE_NAME,
    TOTAL_SHARES
FROM {{ref('tfm_daily_position')}}
WHERE
    (DATE, TRADER, INSTRUMENT, BOOK, STOCK_EXCHANGE_NAME)
    NOT IN
    (
        SELECT DATE, TRADER, INSTRUMENT, BOOK, STOCK_EXCHANGE_NAME
        FROM {{ref('tfm_book')}}
    )
