{{
    config(
        materialized = 'table'
    )
}}

/*
Per TPC-H Spec:
2.4.1 Pricing Summary Report Query (Q1)
*/

SELECT
    F.ORDER_LINE_STATUS_CODE,
    SUM(F.QUANTITY) AS QUANTITY,
    SUM(F.GROSS_ITEM_SALES_AMOUNT) AS GROSS_ITEM_SALES_AMOUNT,
    SUM(F.DISCOUNTED_ITEM_SALES_AMOUNT) AS DISCOUNTED_ITEM_SALES_AMOUNT,
    SUM(F.NET_ITEM_SALES_AMOUNT) AS NET_ITEM_SALES_AMOUNT,

    AVG(F.QUANTITY) AS AVG_QUANTITY,
    AVG(F.BASE_PRICE) AS AVG_BASE_PRICE,
    AVG(F.DISCOUNT_PERCENTAGE) AS AVG_DISCOUNT_PERCENTAGE,

    SUM(F.ORDER_ITEM_COUNT) AS ORDER_ITEM_COUNT

FROM
    {{ ref('fct_order_items') }} AS F
WHERE
    F.SHIP_DATE <= DATEADD('day', -90, {{ var('max_ship_date') }})
GROUP BY
    ORDER_LINE_STATUS_CODE
